##################################
# makefile_gen.py
#
# jcarlin@hmc.edu 6 Sept 2025
# SPDX-License-Identifier: Apache-2.0
#
# Generate Makefile for tests
##################################

import hashlib
import importlib.resources
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import TypedDict

import pyjson5

from act.config import Config
from act.parse_test_constraints import TestMetadata

# Makefile templates
MAKEFILE_HEADER = """
# This Makefile is auto-generated by riscv-arch-test act framework. Do not edit directly.
.DEFAULT_GOAL := compile
.PHONY: compile
"""

OBJDUMP_FLAGS = "-Stsxd -M no-aliases,numeric"


def compute_config_hash(config: Config, xlen: int, e_ext: bool) -> str:
    """Compute a hash of the config options that affect common test compilation.

    Includes the linker script, `rvmodel_macros.h`, the paths to the compiler, reference model,
    and objdump executables, xlen, e_ext, and the memory map from `sail.json` (if present).
    """
    hasher = hashlib.sha256()

    # Hash the architecture parameters
    hasher.update(f"{xlen=}".encode())
    hasher.update(f"{e_ext=}".encode())

    # Hash the linker script contents
    hasher.update(config.linker_script.read_bytes())

    # Hash rvmodel_macros.h contents
    model_test_h = config.dut_include_dir / "rvmodel_macros.h"
    hasher.update(model_test_h.read_bytes())

    # Hash sail.json memory map (if present)
    sail_config = config.dut_include_dir / "sail.json"
    if sail_config.exists():
        sail_data = pyjson5.decode(sail_config.read_text())
        if "memory" in sail_data and "regions" in sail_data["memory"]:
            hasher.update(json.dumps(sail_data["memory"]["regions"], sort_keys=True).encode())

    # Hash executable paths (resolved paths to detect different binaries)
    hasher.update(str(config.compiler_exe.resolve()).encode())
    hasher.update(str(config.ref_model_exe.resolve()).encode())
    if config.objdump_exe is not None:
        hasher.update(str(config.objdump_exe.resolve()).encode())

    return hasher.hexdigest()


def generate_sail_config(xlen: int, e_ext: bool, user_sail_config: Path, common_wkdir: Path) -> Path:
    """Get the path to the internal Sail config file for the given XLEN.

    This config is used for generating signatures for common tests and has
    all extensions enabled.
    """

    # Extract memory map from user's Sail config
    user_sail_config_data = pyjson5.decode(user_sail_config.read_text())
    memory_map = user_sail_config_data["memory"]["regions"]

    # Load internal Sail config template
    internal_sail_config_file = (
        Path(str(importlib.resources.files("act"))) / "data" / f"sail-rv{xlen}{'e' if e_ext else 'i'}.json"
    )
    internal_sail_config = pyjson5.decode(internal_sail_config_file.read_text())

    # Replace memory map
    internal_sail_config["memory"]["regions"] = memory_map

    # Write out modified Sail config to temporary file
    common_sail_config_path = common_wkdir / f"sail-rv{xlen}{'e' if e_ext else 'i'}-common.json"
    common_sail_config_path.parent.mkdir(parents=True, exist_ok=True)
    common_sail_config_path.write_text(pyjson5.encode(internal_sail_config))

    return common_sail_config_path


def gen_compile_targets(
    test_name: Path,
    test_metadata: TestMetadata,
    base_dir: Path,
    xlen: int,
    config: Config,
    sail_config_path: Path,
    debug: bool = False,
) -> str:
    """Generate Makefile targets for compiling a test.

    Args:
        test_name: Name of the test.
        test_metadata: Metadata for the test.
        base_dir: Base directory for the build.
        xlen: XLEN (32 or 64).
        config: Configuration object.
        sail_config_path: Path to a Sail config file for signature generation.
        debug: Whether to generate debug output (signature objdump and trace files).
    """
    # Define paths
    build_dir = base_dir / "build"
    elf_dir = base_dir / "elfs"
    sig_elf = build_dir / test_name.with_suffix(".sig.elf")
    sig_file = build_dir / test_name.with_suffix(".sig")
    result_file = build_dir / test_name.with_suffix(".results")
    sig_trace_file = build_dir / test_name.with_suffix(".sig.trace")
    sig_log_file = build_dir / test_name.with_suffix(".sig.log")
    final_elf = elf_dir / test_name.with_suffix(".elf")

    # Extract metadata
    march = test_metadata.march
    flen = test_metadata.flen
    test_path = test_metadata.test_path
    ref_model_sig_flags = config.ref_model_type.signature_flags.format(sig_file=sig_file, granularity=int(xlen / 8))
    mabi = f"{'i' if xlen == 32 else ''}lp{xlen}{'e' if test_metadata.e_ext else ''}"

    # Generate Makefile targets
    return (
        f"########## Targets for {test_name} ##########\n"
        "# Generate signature based ELF\n"
        f"{sig_elf}: {test_path} | {sig_elf.parent}\n"
        f"\t{config.compiler_string} $(CFLAGS) \\\n"
        f"\t\t-o {sig_elf} \\\n"
        f"\t\t-march={march} -mabi={mabi} -DSIGNATURE -DXLEN={xlen} -DFLEN={flen} \\\n"
        f"\t\t{test_path}\n"
        f"\n"
        # Objdump (only if debug and objdump_exe is set)
        f"{
            f'\n\t{config.objdump_exe} {OBJDUMP_FLAGS} \\\n\t\t{sig_elf} \\\n\t\t> {sig_elf}.objdump\n'
            if debug and config.objdump_exe is not None
            else '# skipping objdump generation\n'
        }"
        "# Generate signature file\n"
        f"{sig_file}: {sig_elf}\n"
        f"\t{config.ref_model_exe} {'--trace-all' if debug else ''} \\\n"
        f"{f'\t\t--trace-output {sig_trace_file} \\\n' if debug else ''}"
        f"\t\t--config {sail_config_path} \\\n"
        f"\t\t{ref_model_sig_flags} \\\n"
        f"\t\t{sig_elf} \\\n"
        f"\t\t> {sig_log_file} 2>&1\n"
        f"\n"
        f"# Modify sig file for inclusion in assembly\n"
        f"{result_file}: {sig_file}\n"
        f"\tuv run sig_modify {sig_file} {xlen}\n"
        f"\n"
        "# Final ELF target\n"
        f"{final_elf}: {sig_elf} {result_file} | {final_elf.parent}\n"
        f"\t{config.compiler_string} $(CFLAGS) \\\n"
        f"\t\t-o {final_elf} \\\n"
        f"\t\t-march={march} -mabi={mabi} -DSELFCHECK -DXLEN={xlen} -DFLEN={flen} \\\n"
        f'\t\t-DSIGNATURE_FILE=\\"{result_file}\\" \\\n'
        f"\t\t{test_path}\n"
        # Objdump (objdump_exe is set)
        f"{
            f'\n\t{config.objdump_exe} {OBJDUMP_FLAGS} \\\n\t\t{final_elf} \\\n\t\t> {final_elf}.objdump\n'
            if config.objdump_exe is not None
            else '# skipping objdump generation\n'
        }"
    )


def gen_rvvi_targets(test_name: Path, base_dir: Path, config: Config) -> str:
    # Define paths
    coverage_dir = base_dir / "coverage"
    elf_dir = base_dir / "elfs"
    elf = elf_dir / test_name.with_suffix(".elf")
    objdump_link = coverage_dir / test_name.with_suffix(".elf.objdump")
    sail_trace = coverage_dir / test_name.with_suffix(".trace")
    sail_log = coverage_dir / test_name.with_suffix(".log")
    rvvi_trace = coverage_dir / test_name.with_suffix(".rvvi")

    # Generate Makefile targets
    return (
        "# Run test on Sail to generate log\n"
        f"{sail_trace}: {elf}\n"
        f"\tln -sf {elf}.objdump {objdump_link} # Create symlink to objdump in coverage directory for easier debugging\n"
        f"\t{config.ref_model_exe} --trace-all \\\n"
        f"\t\t--config {config.dut_include_dir}/sail.json \\\n"  # TODO: don't hardcode sail config file
        f"\t\t{elf} \\\n"
        f"\t\t--trace-output {sail_trace} \\\n"
        f"\t\t> {sail_log} 2>&1\n"
        f"\n"
        "# Generate RVVI trace\n"
        f"{rvvi_trace}: {sail_trace}\n"
        f"\tuv run sail-to-rvvi \\\n"
        f"\t\t{sail_trace} \\\n"
        f"\t\t{rvvi_trace}\n"
    )


def write_makefile(
    makefile_path: Path,
    main_targets: list[tuple[str, list[Path], str]],
    directory_set: set[str],
    makefile_lines: list[str],
) -> None:
    """Write out a Makefile."""
    # Create top-level targets
    for variable_name, targets, command in main_targets:
        makefile_lines.append(f"{variable_name} = \\")
        makefile_lines.extend(f"\t{target} \\" for target in targets)
        makefile_lines.append(f"\n{command}: $({variable_name})\n")

    # Directory creation rules
    makefile_lines.extend([f"{' '.join(sorted(directory_set))}:", "\tmkdir -p $@", ""])

    # Write out Makefile
    makefile_path.parent.mkdir(parents=True, exist_ok=True)
    makefile_path.write_text("\n".join(makefile_lines))


def generate_common_makefile(
    config: Config,
    common_test_list: dict[str, TestMetadata],
    tests_dir: Path,
    common_wkdir: Path,
    xlen: int,
    e_ext: bool,
    debug: bool,
) -> None:
    """Generate a Makefile to compile the common tests.

    Common tests use an internal Sail config with all extensions enabled for
    signature generation, rather than the user's config file.

    Args:
        config: Configuration object.
        common_test_list: Dictionary of common tests.
        tests_dir: Path to tests directory.
        common_wkdir: Working directory for common tests.
        xlen: XLEN (32 or 64).
        e_ext: Whether the 'E' extension is enabled.
        debug: Whether to generate debug output (signature objdump and trace files).
    """
    # Define paths
    common_elf_dir = common_wkdir / "elfs"
    common_build_dir = common_wkdir / "build"

    # Generate maximal Sail config with all extensions enabled and memory map from user's config
    common_sail_config = generate_sail_config(xlen, e_ext, config.dut_include_dir / "sail.json", common_wkdir)

    # Makefile targets
    directory_set: set[str] = set()
    test_targets: list[Path] = []
    makefile_lines = [
        MAKEFILE_HEADER,
        f"CFLAGS += -O0 -g -mcmodel=medany -nostdlib -I{tests_dir}/env -I{tests_dir}/priv/headers",
        f"XLEN := {xlen}",
    ]

    # Build Makefile targets for each test
    for test_name, test_metadata in sorted(common_test_list.items()):
        test_name = Path(test_name)
        elf_name = test_name.with_suffix(".elf")
        final_elf = common_elf_dir / elf_name
        test_targets.append(final_elf)
        directory_set.update([str((common_elf_dir / test_name).parent), str((common_build_dir / test_name).parent)])
        makefile_lines.append(
            gen_compile_targets(test_name, test_metadata, common_wkdir, xlen, config, common_sail_config, debug)
        )

    # Write out Makefile
    makefile_path = common_wkdir / f"Makefile-rv{xlen}{'e' if e_ext else 'i'}.mk"
    write_makefile(makefile_path, [("ELFS", test_targets, "compile")], directory_set, makefile_lines)


def generate_config_makefile(
    config: Config,
    config_test_list: dict[str, TestMetadata],
    common_test_list: dict[str, TestMetadata],
    tests_dir: Path,
    coverpoint_dir: Path,
    wkdir: Path,
    config_name: str,
    xlen: int,
    common_dir: str,
    coverage_enabled: bool,
    debug: bool = False,
) -> None:
    """Generate a Makefile to compile the config-specific tests.

    Args:
        config: Configuration object.
        config_test_list: Dictionary of config-specific tests.
        common_test_list: Dictionary of common tests.
        tests_dir: Path to tests directory.
        coverpoint_dir: Path to coverpoint directory.
        wkdir: Working directory.
        config_name: Name of the configuration.
        xlen: XLEN (32 or 64).
        common_dir: directory to generate common tests in. Hash specific.
        coverage_enabled: Whether coverage generation is enabled.
        debug: Whether to generate debug output (signature objdump and trace files).
    """
    # Define paths
    config_wkdir = wkdir / config_name
    config_elf_dir = config_wkdir / "elfs"
    config_build_dir = config_wkdir / "build"
    config_coverage_dir = config_wkdir / "coverage"
    config_report_dir = config_wkdir / "reports"
    common_wkdir = wkdir / common_dir
    common_elf_dir = common_wkdir / "elfs"

    # Makefile targets
    directory_set: set[str] = set()
    test_targets: list[Path] = []
    coverage_targets: dict[Path, list[Path]] = {}
    makefile_lines = [
        MAKEFILE_HEADER,
        f"CFLAGS += -O0 -g -mcmodel=medany -nostdlib -I{tests_dir}/env -I{tests_dir}/priv/headers",
        f"XLEN := {xlen}",
    ]

    # Build Makefile targets for each test
    for test_name, test_metadata in sorted(config_test_list.items()):
        # Test specific paths
        test_name = Path(test_name)
        elf_name = test_name.with_suffix(".elf")
        final_elf = config_elf_dir / elf_name
        trace_name = test_name.with_suffix(".rvvi")
        trace_path = config_coverage_dir / trace_name
        sail_config_path = config.dut_include_dir / "sail.json"

        # Add test to target lists
        test_targets.append(final_elf)
        directory_set.update([str((config_elf_dir / test_name).parent), str((config_build_dir / test_name).parent)])

        # Generate compilation/symlink targets
        if str(test_name) in common_test_list:
            common_elf = common_elf_dir / elf_name
            makefile_lines.append(
                f"# Create symlink to common elf for {test_name}\n"
                f"{final_elf}: {common_elf} | {final_elf.parent}\n"
                f"\tln -sf {common_elf} \\\n"
                f"\t\t{final_elf}\n"
                f"{
                    f'\tln -sf {common_elf}.objdump \\\n\t\t{final_elf}.objdump\n'
                    if config.objdump_exe is not None
                    else '\t# skipping objdump generation\n'
                }"
            )
        else:
            makefile_lines.append(
                gen_compile_targets(test_name, test_metadata, config_wkdir, xlen, config, sail_config_path, debug)
            )

        # Generate coverage trace targets
        if coverage_enabled:
            if trace_path.parent not in coverage_targets:
                coverage_targets[trace_path.parent] = []
            coverage_targets[trace_path.parent].append(trace_path.absolute())
            makefile_lines.append(gen_rvvi_targets(test_name, config_wkdir, config))
            makefile_lines.append("\n")

    main_targets = [("ELFS", test_targets, "compile")]

    # Generate coverage targets
    if coverage_enabled:
        coverage_makefile_lines, coverage_reports = gen_coverage_targets(
            coverage_targets,
            coverpoint_dir,
            config_coverage_dir,
            config_report_dir,
            config.dut_include_dir,  # TODO: coverage config dir should be generated from UDB
        )
        makefile_lines.append(coverage_makefile_lines)
        main_targets.append(("COVERAGE_REPORTS", coverage_reports, "coverage"))

    # Write out Makefile
    makefile_path = config_wkdir / "Makefile"
    write_makefile(
        makefile_path,
        main_targets,
        directory_set,
        makefile_lines,
    )


def gen_coverage_targets(
    coverage_targets: dict[Path, list[Path]],
    coverpoint_dir: Path,
    base_dir: Path,
    config_report_dir: Path,
    dut_header_dir: Path,
) -> tuple[str, list[Path]]:
    """Generate coverage targets and tracelists."""
    # Generate tracelist file for each extension/test group and a target to generate the UCDB coverage file
    makefile_lines = ["#################### Coverage targets ####################\n"]
    coverage_reports: list[Path] = []
    for coverage_group, traces in sorted(coverage_targets.items()):
        # Define paths
        base_name = base_dir / coverage_group / coverage_group.stem
        tracelist_file = base_name.with_suffix(".tracelist")
        ucdb_file = base_name.with_suffix(".ucdb")
        work_dir = base_name.parent / "ucdb_work"
        report_file_base = config_report_dir / coverage_group.stem
        summary_file = Path(f"{report_file_base}_summary.txt")

        # Write the tracefile
        tracelist_file.parent.mkdir(parents=True, exist_ok=True)
        tracelist_file.write_text(
            f"# Tests for coverage group: {coverage_group}\n"
            "# Generated automatically by riscv-arch-test act framework\n"
            + "\n".join([str(trace) for trace in sorted(traces)])
        )

        # Add UCDB file to the list
        with (
            importlib.resources.path("act", "fcov") as fcov_path,
            importlib.resources.path("act", "riscv-arch-test.do") as vsim_do_path,
        ):
            makefile_lines.append(
                f"# Generate UCDB file for {coverage_group.stem}\n"
                f"{ucdb_file}: {' '.join([str(trace) for trace in sorted(traces)])}\n"
                f'\tvsim -c -do "do {vsim_do_path.absolute()} \\\n'
                f"\t\t{tracelist_file}\\\n"
                f"\t\t{ucdb_file}\\\n"
                f"\t\t{work_dir}\\\n"
                f"\t\t{fcov_path.absolute()}\\\n"
                f"\t\t{coverpoint_dir}\\\n"
                f"\t\t{dut_header_dir}\\\n"
                f'\t\t{{{coverage_group.stem.upper()}_COVERAGE}}" > {ucdb_file}.log\n'
            )

        # Generate coverage report
        coverage_reports.append(summary_file)
        makefile_lines.append(
            f"# Generate coverage report for {coverage_group.stem}\n"
            f".PHONY: {coverage_group.stem}-report\n"
            f"{coverage_group.stem}-report: {summary_file}\n"
            f"{summary_file}: {ucdb_file}\n"
            f"\tuv run coverreport\\\n"
            f"\t\t{ucdb_file}\\\n"
            f"\t\t{report_file_base}\n"
        )

    # Generate overall summary target that concatenates all individual summaries
    if coverage_reports:
        overall_summary = config_report_dir / "_overall_summary.txt"
        # Use merge_summaries script to properly format the combined output
        summary_files = " ".join([str(s) for s in sorted(coverage_reports)])

        # how to remove all coverage reports after merging
        makefile_lines.append(
            f"# Clean up individual coverage summaries after merging\n"
            f".PHONY: clean-coverage-summaries\n"
            f"clean-coverage-summaries:\n"
            f"\trm -f {' '.join([str(s) for s in sorted(coverage_reports) if s != overall_summary])}\n"
        )

        makefile_lines.append(
            f"# Generate overall coverage summary by merging all individual summaries\n"
            f"{overall_summary}: {summary_files}\n"
            f"\tuv run merge-summaries {overall_summary} {summary_files}\n"
            f"\t$(MAKE) clean-coverage-summaries # remove individual coverage summaries after merging\n"
        )
        coverage_reports.append(overall_summary)

    return ("\n".join(makefile_lines), coverage_reports)


class ConfigData(TypedDict):
    """Type definition for configuration data dictionary."""

    config: Config
    xlen: int
    e_ext: bool
    selected_tests: dict[str, TestMetadata]


@dataclass
class CommonGroup:
    """A group of configs that share a common test directory."""

    config: Config  # Representative config (for compiler/linker paths)
    xlen: int
    e_ext: bool
    common_tests: dict[str, TestMetadata] = field(default_factory=dict)
    configs: list[ConfigData] = field(default_factory=list)


def generate_makefiles(
    configs: list[ConfigData],
    tests_dir: Path,
    coverpoint_dir: Path,
    workdir: Path,
    coverage_enabled: bool,
    debug: bool = False,
) -> None:
    """Generate Makefiles for multiple configurations with shared common directories.

    Configs with the same hash share a common directory named common/{hash[:8]}.
    Only common tests needed by at least one config in a group are compiled.

    Args:
        configs: List of configuration data dictionaries.
        tests_dir: Path to tests directory.
        coverpoint_dir: Path to coverpoint directory.
        workdir: Working directory.
        coverage_enabled: Whether coverage generation is enabled.
        debug: Whether to generate debug output (signature objdump and trace files).

    """
    # Pass 1: Group configs by hash and compute union of needed common tests
    common_groups: dict[str, CommonGroup] = {}

    for config_data in configs:
        # Unpack config data
        config = config_data["config"]
        xlen = config_data["xlen"]
        e_ext = config_data["e_ext"]

        # Compute config hash and add to list of hashes if needed
        config_hash = compute_config_hash(config, xlen, e_ext)
        if config_hash not in common_groups:
            common_groups[config_hash] = CommonGroup(config=config, xlen=xlen, e_ext=e_ext)

        # Add this config to the appropriate common list based on hash and add tests to that common list
        common_group = common_groups[config_hash]
        common_group.configs.append(config_data)
        common_group.common_tests.update(
            {
                test: metadata
                for test, metadata in config_data["selected_tests"].items()
                if not metadata.config_dependent
            }
        )

    # Pass 2: Generate Makefiles
    top_makefile_lines = [MAKEFILE_HEADER]
    compile_targets: list[str] = []
    coverage_targets: list[str] = []

    for config_hash, common_group in common_groups.items():
        arch_key = f"rv{common_group.xlen}{'e' if common_group.e_ext else 'i'}"
        common_dir = f"common/{config_hash[:8]}"
        common_compile_target = f"common-{config_hash[:8]}-{arch_key}-compile"

        # Generate common Makefile for this group
        generate_common_makefile(
            common_group.config,
            common_group.common_tests,
            tests_dir,
            workdir / common_dir,
            common_group.xlen,
            common_group.e_ext,
            debug,
        )
        top_makefile_lines.extend(
            [
                f"{common_compile_target}:",
                f"\t$(MAKE) -f {common_dir}/Makefile-{arch_key}.mk compile",
                "",
            ]
        )

        # Generate config Makefiles for each config in this common group
        for config_data in common_group.configs:
            config = config_data["config"]
            compile_targets.append(f"{config.name}-compile")
            coverage_targets.append(f"{config.name}-coverage")
            top_makefile_lines.extend(
                [
                    f"{config.name}-compile: {common_compile_target}",
                    f"\t$(MAKE) -C {config.name} compile",
                    "",
                ]
            )
            if coverage_enabled:
                top_makefile_lines.extend(
                    [
                        f"{config.name}-coverage: {config.name}-compile",
                        f"\t$(MAKE) -C {config.name} coverage",
                        "",
                    ]
                )

            generate_config_makefile(
                config,
                config_data["selected_tests"],
                common_group.common_tests,
                tests_dir,
                coverpoint_dir,
                workdir,
                config.name,
                common_group.xlen,
                common_dir,
                coverage_enabled,
                debug,
            )

    top_makefile_lines.append(f"compile: {' '.join(compile_targets)}")
    if coverage_enabled:
        top_makefile_lines.append(f"coverage: {' '.join(coverage_targets)}")
    (workdir / "Makefile").write_text("\n".join(top_makefile_lines))
